export function handleError() {
	return { message: 'Internal Error' }; // implementation mặc định của hook này
}
