export function handleError() {
	return { message: 'Internal Error' }; // cấu hình mặc định của hook này
}
